
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-system
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: flask-container
        image: heyrohhh/student-flask-app:v2 
        ports:
        - containerPort: 5000 
---
# --- THE SERVICE TO MAKE IT VISIBLE ---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  type: LoadBalancer
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 5000 